run:
  timeout: 10m
  # skip-dirs:
  # skip-files:
  
linters:
  enable-all: false
  enable:
    - megacheck
    - govet
    - gocyclo
    - unused
    - gofmt
    - revive
    - misspell
    - exportloopref
    - nolintlint
  disable-all: false
  disable:
    - prealloc
    - scopelint
    - golint
    - asasalint
  presets:
    - bugs
    - unused
  fast: false

linters-settings:
  # govet:
  #   enable-all: true
  #   settings:
  #     fieldalignment:
  #       suggest-new: true
      
  revive:
    # Enable all available rules.
    # Default: false
    # enable-all-rules: true
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#dot-imports
      - name: dot-imports
        disabled: true
  exhaustive:
    # check switch statements in generated files also
    check-generated: false
    # indicates that switch statements are to be considered exhaustive if a
    # 'default' case is present, even if all enum members aren't listed in the
    # switch
    default-signifies-exhaustive: true
  nolintlint:
    # Disable to ensure that all nolint directives actually have an effect.
    # Default: false
    allow-unused: false
    # Exclude following linters from requiring an explanation.
    # Default: []
    allow-no-explanation: []
    # Enable to require an explanation of nonzero length after each nolint directive.
    # Default: false
    require-explanation: false
    # Enable to require nolint directives to mention the specific linter being suppressed.
    # Default: false
    require-specific: true